### ISSUE TITLE
Sublime Text Project File

### ISSUE THREAD

**Issue by wazaundtechnik** [tulul/tululbot#12]
What is our line ending? LF, right? But when we edit in ST Windows, by default it will be CRLF.

How about line indentation? etc, etc, etc.

We need to standardize our style into IDE-specific settings.

**Comment by kemskems** [comment]
The standard style guide for Python code is documented in [PEP 8](http://legacy.python.org/dev/peps/pep-0008/) and [PEP 257](http://legacy.python.org/dev/peps/pep-0257/). `flake8` will check for PEP 8. There is also a library to check for PEP 257 but we haven't used it yet.

As for unifying some code styles, I think [editorconfig](http://editorconfig.org/) is a good way to go. Almost every popular text editors support it, either natively or via third-party plugin.

I can write the `.editorconfig` file if everyone agrees.

**Comment by wazaundtechnik** [comment]
Hi kems. Thanks! I think it would be more beautiful if we can use editorconfig.

**Comment by kemskems** [comment]
Great. I'll make the PR then.
