### ISSUE TITLE
Should We Use Unified .env and Use Procfile Locally, Too?

### ISSUE THREAD

**Issue by wazaundtechnik** [tulul/tululbot#15]
(Continuing discussion from #11)

From [Twelve-factor App](http://12factor.net/dev-prod-parity):

>Make the tools gap small: keep development and production as similar as possible.
>
>Summarizing the above into a table:
>
>Dev vs production environments	
> - Traditional app: Divergent	
> - Twelve-factor app: As similar as possible

But as @kemskems mentioned in #11:

> Ada satu concern fid. Kalau lagi nge-dev, enakan nge-run-nya itu python app.py supaya jalan di debug mode (gak pakai gunicorn). Salah satu keuntungannya adalah kalo ada uncaught exception, si Flask bisa tangkap dan kasih stack trace + REPL di browser (assuming via browser nembaknya). Kalau pakai gunicorn ini jadi gak bisa.
>
>Salah satu solusinya adalah, karena config juga dah ditaruh di .env, di file app.py .env-nya di-load dulu. Ada library yg bisa dipake: https://pypi.python.org/pypi/python-dotenv. Tapi cara ini agak aneh juga sih kalo pake honcho jadi 2x ngebaca .env.
>
>Ada ide lain?

So, should we use Local Procfile? There are multiple suggestions:

- Using different Procfile for dev and prod. But this may lead into **not adhering the Twelve Factor.** (Remember, the twelve factor says: Prod and Dev must be as close as possible)
- Simply using env file, but leave Procfile as-is (no-change). We don't use the Procfile locally, only `.env` file.

Meanwhile, i am now in charge to make sure we can use debug-mode too with the same Procfile.

**Comment by wazaundtechnik** [comment]
**Update:**

Somehow i find **we shouldn't use the Procfile locally.** But we *may* want to run the app with Procfile locally to reflect production environment. How about that? So Honcho won't be default. But developers may want to run Honcho to make sure the app still run with production-like environment.

**Comment by kemskems** [comment]
> Somehow i find we shouldn't use the Procfile locally.

Can you post the reference here? I'd like to read about that too.

Anyway, I don't mind putting the configuration in `.env` file. And to load them whenever you run `python tululbot.py` you can do it like so:

```python
# In tululbot.py
from os import environ
from os.path import join, dirname
from dotenv import load_dotenv

# ...do stuff here...

if __name__ == '__main__':
    # Load .env file
    dotenv_path = join(dirname(__file__), '.env')
    load_dotenv(dotenv_path)

    # Create the app using config from env vars
    app = create_app({
        'DEBUG': environ.get('DEBUG') == 'true',
        'TELEGRAM_BOT_TOKEN': environ.get('TELEGRAM_BOT_TOKEN', ''),
        'LOG_LEVEL': environ.get('LOG_LEVEL', 'WARNING')
    })

    # Run the app
    app.run()
```

`dotenv` is a third-party library. You can see more about it [here](https://github.com/theskumar/python-dotenv).

**Comment by wazaundtechnik** [comment]
Also see #11. Settled in #39.

**Comment by kemskems** [comment]
@wazaundtechnik Now that we have `.env` file, shouldn't the option of using Honcho be explained in `README.md`?
