### ISSUE TITLE
Dispatcher Refactor

### ISSUE THREAD

**Issue by wazaundtechnik** [tulul/tululbot#23]
```python
            if text is not None:
                if text.startswith('/wiki'):
                    term = text[6:]
                    if term:
                        return reply(wiki(term))
                    return reply('Masukin kata kunci pencarian lah')
                elif text.startswith('/ngelely'):
                    term = text[9:]
                    if term:
                        qs = urlencode(dict(q=term))
                        google_url = 'https://www.google.co.id/#{}'.format(qs)
                        return reply('Jangan nge-lely\n{}'.format(google_url))
                elif text == '/who':
                    about_text = (
                        'telebot untuk tulul :v\n'
                        'dibuat dengan Python 3.4 dan cinta\n'
                        'baru bisa ngewiki dan ngelely doang\n'
                        'kontribusi di https://github.com/tulul/tululbot'
                    )
                    return reply(about_text)
```

Uh, else if else if, indentation. Remember: Too much if-else branch is dangerous. How about we create class and its function for dispatcher?

So to make use of dispatcher, we can simply:

```python
# create new class, command_list.py
class CommandList
    def wiki(self): # 1 command == 1 function. Beautiful, eh?
    def ngeleli(self):
    def quotes(self):

# at tululbot.py
if (message is not None):
    result = dispatcher.dispatch(CommandList)
    if (result is not None):
        return reply(result)
```

**Comment by kemskems** [comment]
Upon reading this, I realize that our bot command is very similar with command line. There are a number of great command line creator libraries ([argparse](https://docs.python.org/dev/library/argparse.html), [Click](http://click.pocoo.org/5/), etc). I think we can follow their pattern.

Basically, creating command is as easy as defining a decorated function:

```python
@bot.command
@bot.option('term', nargs=bot.REMAINDER)
def leli(term):
    # code goes here

bot.run_command(text)  # text is obtained from webhook
```

The code above is just an illustration but I think you get the idea.

**Comment by kemskems** [comment]
I'm labeling this as low priority since the number of commands is still low.

**Comment by wazaundtechnik** [comment]
> I'm labeling this as low priority since the number of commands is still low.

I changed it to normal priority. We can't leave the code broken. [In Pragmatic Programmer, you can't leave a program broken]:

> While software development is immune from almost all physical laws, entropy hits us hard. Entropy is a term from physics that refers to the amount of “disorder” in a system. Unfortunately, the laws of thermodynamics guarantee that the entropy in the universe tends toward a maximum. When disorder increases in software, programmers call it “software rot.”
>
>There are many factors that can contribute to software rot. The most important one seems to be the psychology, or culture, at work on a project. Even if you are a team of one, your project’s psychology can be a very delicate thing. Despite the best laid plans and the best people, a project can still experience ruin and decay during its lifetime. Yet there are other projects that, despite enormous difficulties and constant setbacks, successfully fight nature’s tendency toward disorder and manage to come out pretty well.
>
>What makes the difference?
>
>In inner cities, some buildings are beautiful and clean, while others are rotting hulks. Why? Researchers in the field of crime and urban decay discovered a fascinating trigger mechanism, one that very quickly turns a clean, intact, inhabited building into a smashed and abandoned derelict .
>
>A broken window.
>
>One broken window, left unrepaired for any substantial length of time, instills in the inhabitants of the building a sense of abandonment—a sense that the powers that be don’t care about the building. So another window gets broken. People start littering. Graffiti appears. Serious structural damage begins. In a relatively short space of time, the building becomes damaged beyond the owner’s desire to fix it, and the sense of abandonment becomes reality.
>
>The “Broken Window Theory” has inspired police departments in New York and other major cities to crack down on the small stuff in order to keep out the big stuff. It works: keeping on top of broken windows, graffiti, and other small infractions has reduced the serious crime level.
>
>Don’t Live with Broken Windows
>
>Don’t leave “broken windows” (bad designs, wrong decisions, or poor code) unrepaired. Fix each one as soon as it is discovered. If there is insufficient time to fix it properly, then board it up. Perhaps you can comment out the offending code, or display a “Not Implemented” message, or substitute dummy data instead. Take some action to prevent further damage and to show that you’re on top of the situation.
>
>We’ve seen clean, functional systems deteriorate pretty quickly once windows start breaking. There are other factors that can contribute to software rot, and we’ll touch on some of them elsewhere, but neglect accelerates the rot faster than any other factor.
>
>You may be thinking that no one has the time to go around cleaning up all the broken glass of a project. If you continue to think like that, then you’d better plan on getting a dumpster, or moving to another neighborhood. Don’t let entropy win.
>
>Putting Out Fires  
>By contrast, there’s the story of an obscenely rich acquaintance of Andy’s. His house was immaculate, beautiful, loaded with priceless antiques, objets d’art, and so on. One day, a tapestry that was hanging a little too close to his living room fireplace caught on fire. The fire department rushed in to save the day—and his house. But before they dragged their big, dirty hoses into the house, they stopped—with the fire raging—to roll out a mat between the front door and the source of the fire.
>
>They didn’t want to mess up the carpet.
>
>A pretty extreme case, to be sure, but that’s the way it must be with software. One broken window—a badly designed piece of code, a poor management decision that the team must live with for the duration of the project—is all it takes to start the decline. If you find yourself working on a project with quite a few broken windows, it’s all too easy to slip into the mindset of “All the rest of this code is crap, I’ll just follow suit.” It doesn’t matter if the project has been fine up to this point. In the original experiment leading to the “Broken Window Theory,” an abandoned car sat for a week untouched. But once a single window was broken, the car was stripped and turned upside down within hours.
>
>By the same token, if you find yourself on a team and a project where the code is pristinely beautiful—cleanly written, well designed, and elegant—you will likely take extra special care not to mess it up, just like the firefighters. Even if there’s a fire raging (deadline, release date, trade show demo, etc.), you don’t want to be the first one to make a mess.

[In Pragmatic Programmer, you can't leave a program broken]: https://pragprog.com/the-pragmatic-programmer/extracts/software-entropy

**Comment by kemskems** [comment]
Thanks. This is very enlightening. I really need to read the complete book sometime.

**Comment by fushar** [comment]
I'm changing the priority to high.

**Comment by wazaundtechnik** [comment]
Done by #39
