### ISSUE TITLE
Disable preview on google result and `/who` command

### ISSUE THREAD

**Issue by kemskems** [tulul/tululbot#29]
The preview on those two scenarios are annoying. It's better to disable them. This should be easy. We only need to change `reply` function to accept a keyword argument:

```python
def reply(reply_text, disable_preview=False):
    payload = {
        'method': 'sendMessage',
        'chat_id': chat_id,
        'text': reply_text,
        'disable_web_page_preview': 'false' if not disable_preview else 'true',
        'reply_to_message_id': message['message_id']
    }
    return jsonify(**payload)
```

**Comment by kemskems** [comment]
@indraep since you've setup your machine, you might want to work on this.

**Comment by indraep** [comment]
Oke, give me a try. Thankyou

**Comment by wazaundtechnik** [comment]
Hi dro. Thanks for taking care this issue. Any update for this?

**Comment by wazaundtechnik** [comment]
Hi @indraep this has been done, hasn't it? I close it then.
