### ISSUE TITLE
Use URL Encoding for Ngelely

### ISSUE THREAD

**Issue by wazaundtechnik** [tulul/tululbot#3]
So space is not "literal space"

![2015-09-28_19-54-10](https://cloud.githubusercontent.com/assets/14859957/10135774/ca4f4a8e-661a-11e5-900f-504f36f9d737.png)

**Comment by iqbalmineraltown** [comment]
just replace that space with `+`

**Comment by kemskems** [comment]
No one working on this yet? I'll grab this task then.
