### ISSUE TITLE
Better Error Handling

### ISSUE THREAD

**Issue by wazaundtechnik** [tulul/tululbot#31]
Which is better?

- If error happens, throw 500 as response, or
- if error happens, throw 200 with "Error" message.

**Comment by kemskems** [comment]
I'd argue responding with 200 is better. This is because Telegram will keep trying to send the same update repeatedly to our bot if we respond with 500. We still need to log the error though so we know shit happens. And I think we can log the error to our devel chatroom/email.

**Comment by kemskems** [comment]
This is done by #39. Basically in non-debug mode, when an uncaught error is raised, a notification will be sent to our devel group, along with its stack trace. It then responds with 200 status code to Telegram to prevent it spamming the same update.
