### ISSUE TITLE
Initial Travis Test for Tululbot

### ISSUE THREAD

**Issue by wazaundtechnik** [tulul/tululbot#5]
Currently, Tululbot is designed to be run on specific machine (Heroku and local). Tululbot is not designed to be tested and run locally.

This also means to refactor the Tululbot so it is testable. (cc @fushar)

**Comment by kemskems** [comment]
Agree. This morning I tried to write some tests for tululbot but haven't finished it yet. I think we can use [Flask Testing](https://pythonhosted.org/Flask-Testing/) for this.

**Comment by wazaundtechnik** [comment]
Hi kems. Thanks for suggestion. Since i am new to python, perhaps the initial is to make this repo compliant with Travis. We can incrementally build the test after this.
