### ISSUE TITLE
Make leli command respond when user does not specify the query

### ISSUE THREAD

**Issue by kemskems** [tulul/tululbot#53]
Just like what imagebot does. When someone says `/leli`, without the argument/query, TululBot should reply to that person "Apa yang mau dileli?". When the person says the query, it will be automatically sent as reply to the bot's question. The bot then responds by sending the result of `/leli <query>` to the person.

**Comment by kemskems** [comment]
It seems this is not as easy as I thought it would. This is because our `CommandDispatcher` only checks whether a given text matches one of the command regexes. To implement this feature, we cannot merely check the text. We also need to check whether the update is a reply to our bot. And not just any reply; it should be a reply to our bot message asking what to leli. I think this is cannot be achieved with our current design.

Thus, I propose the following:

1. Commands should be implemented as classes, each with two required methods: `check()` and `run()` (these names are subject to change). `check()` accepts an update object as its argument and returns whether the update object matches the criteria for that command (e.g. for our current `leli` command, this simply checks whether the text matches `r'^/leli (.+)$'` regex). `run()`, if invoked, will do the actual command and return a dictionary which is compatible with what [Telegram's `sendMessage` method expects](https://core.telegram.org/bots/api#sendmessage), except for the `chat_id` and `reply_to_message_id` property since it is handled by `main()` view.

2. `CommandDispatcher` should be refactored so that `add_command()` method accepts a command instance as its argument. Its `run_command()` method (might be renamed) can then simply accept an update object, select a command whose `.check()` method returns `True` given the update object, invoke the command `.run()` method, and return its return value.

3. (Optional) Note that above I used the term "update object". This can be implemented as a simple dictionary, named tuple, or an instance of a class. If necessary, we can create a class for `Update`, `Message`, and other Telegram entities. We might use [twx.botapi library](http://pythonhosted.org/twx.botapi/index.html) or implement ourselves. In my opinion, the library is poorly documented so implementing ourselves might be a better idea. It can be treated as a separate project/repo too.

With this design, this feature is feasible to implement since all commands have full access to an update object. It can check not only the text but also whether an update is a reply, to whom it was sent, etc.

What do you guys think?

**Comment by wazaundtechnik** [comment]
I am sorry, i was pointing wrong commit id : ( Ignore the wrong build.

**Comment by kemskems** [comment]
This is done.
