### ISSUE TITLE
Typo in /ngelely command

### ISSUE THREAD

**Issue by fushar** [tulul/tululbot#6]
I think it should be `/ngeleli` or `/leli`.

**Comment by rolandhawk** [comment]
prefer `/leli`, lebih singkat

**Comment by iqbalmineraltown** [comment]
why not `/lely` ?

**Comment by wazaundtechnik** [comment]
Once we can read the entire message, we can make alias for this and make this conversational.

**Comment by fushar** [comment]
@iqbalmineraltown because her real name is `Nurlaili`?

**Comment by iqbalmineraltown** [comment]
@fushar k, `leli` it is

**Comment by nurlailifajriyah** [comment]
why don't try other word without leli or lely for this command?

**Comment by rolandhawk** [comment]
so, is it `/leli`?

**Comment by wazaundtechnik** [comment]
So guys, do we have accordance for this? We should close this issue asap since it depends to Botfather registration.

**Comment by rolandhawk** [comment]
yeah, it's `/leli`

**Comment by fushar** [comment]
+1 for `/leli`

**Comment by nurlailifajriyah** [comment]
-1 for /leli
I think it should be verb, something with "nge-" looks okay

**Comment by iqbalmineraltown** [comment]
`/leli` it is. Case losed
