### ISSUE TITLE
Merge /wiki + /ngelely commands into one single command

### ISSUE THREAD

**Issue by fushar** [tulul/tululbot#7]
Proposal:

We only have `/ngelely` command. It will first search in Wikipedia. If no articles found, then resort to google search result.

**Comment by wazaundtechnik** [comment]
Please also take a look for #3. We have a little bit problem on URL encoding.

**Comment by wazaundtechnik** [comment]
@fushar any ETA for this?

**Comment by fushar** [comment]
@wazaundtechnik this noon.
