### ISSUE TITLE
Use Submodule

### ISSUE THREAD

**Issue by wazaundtechnik** [tulul/tululbot#9]
And integrate with tulul/tulul-quotes

**Comment by fushar** [comment]
I don't think this is necessary. From my experience, submodules complicate development. We can just treat `tulul-quotes` as an external resource.

It's a subjective opinion, though.

**Comment by wazaundtechnik** [comment]
So if that is the case, how should we implement the /quote command?

I have two proposals:

1. Use submodule: By default, Heroku will recursively pull the submodule too. And since we have all of the data locally, we can simply read the yml from file.
1. Use Github API to retrieve that yml file from master branch, cache it at start (or every 5 minutes) to reduce network overhead.

What do you think? So you don't prefer first option?

**Comment by fushar** [comment]
You can just `wget https://raw.githubusercontent.com/tulul/tulul-quotes/master/quote.yaml`.

**Comment by kemskems** [comment]
+1 @fushar 's idea. If the quote rarely changes, we can even load it once and store it on memory; restarting the app whenever a new quote is added. I think it's simpler.

**Comment by wazaundtechnik** [comment]
Thanks. Settled. So no submodule for now. If something is changing in the future, feel free to reopen this.
